export type PosterFormat = "whatsapp" | "instagram";
export type TemplateKey = "rising-sun" | "heritage" | "modern-lines";
export const FORMATS = { whatsapp:{label:"WhatsApp Portrait",width:1080,height:1920,ratio:"9:16"}, instagram:{label:"Instagram Portrait",width:1080,height:1350,ratio:"4:5"} } as const;
export const TEMPLATES = [{id:"rising-sun",name:"எழுச்சி",note:"Bold red, black & gold"},{id:"heritage",name:"மரபு",note:"Editorial cream & crimson"},{id:"modern-lines",name:"முன்னேற்றம்",note:"Clean geometric layout"}] as const;
export type RenderInput = { fullName:string; designation:string; approvedContent:string; photoUrl:string; symbolUrl?:string|null; format:PosterFormat; template:TemplateKey };
function wrap(ctx:CanvasRenderingContext2D,text:string,maxWidth:number){const words=text.trim().split(/\s+/),lines:string[]=[];let line="";for(const word of words){const next=line?`${line} ${word}`:word;if(ctx.measureText(next).width>maxWidth&&line){lines.push(line);line=word}else line=next}if(line)lines.push(line);return lines}
function load(url:string){return new Promise<HTMLImageElement>((resolve,reject)=>{const el=new Image();el.crossOrigin="anonymous";el.onload=()=>resolve(el);el.onerror=reject;el.src=url})}
function cover(ctx:CanvasRenderingContext2D,img:HTMLImageElement,x:number,y:number,w:number,h:number){const scale=Math.max(w/img.width,h/img.height),sw=w/scale,sh=h/scale;ctx.drawImage(img,(img.width-sw)/2,(img.height-sh)/2,sw,sh,x,y,w,h)}
export async function renderPoster(canvas:HTMLCanvasElement,input:RenderInput){const {width:w,height:h}=FORMATS[input.format];canvas.width=w;canvas.height=h;const ctx=canvas.getContext("2d");if(!ctx)throw new Error("Canvas unavailable");const photo=await load(input.photoUrl);const modern=input.template==="modern-lines",heritage=input.template==="heritage",light=!heritage&&!modern,accent=heritage?"#8e1c24":"#b42327";ctx.fillStyle=heritage?"#f2e8d5":modern?"#f5f2ea":"#171411";ctx.fillRect(0,0,w,h);ctx.fillStyle=accent;if(modern){ctx.fillRect(0,0,w,h*.08);ctx.fillRect(0,h*.92,w,h*.08)}else{ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(w,0);ctx.lineTo(w,h*.2);ctx.lineTo(0,h*.32);ctx.closePath();ctx.fill()}const px=modern?w*.12:w*.08,py=modern?h*.16:h*.23,pw=modern?w*.76:w*.84,ph=input.format==="whatsapp"?h*.42:h*.43;ctx.save();ctx.beginPath();if(heritage)ctx.ellipse(w/2,py+ph/2,pw/2,ph/2,0,0,Math.PI*2);else ctx.roundRect(px,py,pw,ph,42);ctx.clip();cover(ctx,photo,px,py,pw,ph);ctx.restore();ctx.strokeStyle="#d49a29";ctx.lineWidth=12;ctx.strokeRect(px,py,pw,ph);ctx.fillStyle=light?"#fff":"#171411";ctx.textAlign="center";ctx.font=`800 ${input.format==="whatsapp"?60:50}px "Noto Sans Tamil",Latha,sans-serif`;const my=py+ph+h*.06,lines=wrap(ctx,input.approvedContent,w*.82).slice(0,4);lines.forEach((line,i)=>ctx.fillText(line,w/2,my+i*78));const iy=my+lines.length*78+48;ctx.fillStyle=accent;ctx.font=`900 ${input.format==="whatsapp"?68:58}px "Noto Sans Tamil",Latha,sans-serif`;ctx.fillText(input.fullName.trim(),w/2,iy);ctx.fillStyle=light?"#f7f1e5":"#39322b";ctx.font=`600 ${input.format==="whatsapp"?37:32}px "Noto Sans Tamil",Latha,sans-serif`;ctx.fillText(input.designation.trim(),w/2,iy+62);ctx.fillStyle="#d49a29";ctx.fillRect(w*.38,iy+93,w*.24,8);if(input.symbolUrl){try{const symbol=await load(input.symbolUrl);ctx.drawImage(symbol,w-190,44,130,130)}catch{}}ctx.fillStyle=light?"#b8aa98":"#756b5e";ctx.font="500 24px system-ui,sans-serif";ctx.fillText("ADMIN-APPROVED CONTENT",w/2,h-56)}
