"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { contentSchema } from "@/lib/validation";
async function requireAdmin(){const db=await createSupabaseServerClient();const {data:{user}}=await db.auth.getUser();if(!user)redirect("/admin/login");const {data:isAdmin,error}=await db.rpc("is_admin");if(error||!isAdmin)throw new Error("Administrator access required.");return {db,user}}
export async function signIn(form:FormData){const db=await createSupabaseServerClient();const email=String(form.get("email")).trim(),password=String(form.get("password"));const {data,error}=await db.auth.signInWithPassword({email,password});if(error)redirect(`/admin/login?error=${encodeURIComponent(error.message)}`);if(!data.user)redirect("/admin/login?error=Sign-in%20failed.%20Please%20try%20again.");const {data:isAdmin,error:roleError}=await db.rpc("is_admin");if(roleError||!isAdmin){await db.auth.signOut();redirect(`/admin/login?error=${encodeURIComponent(roleError?.message||"This user does not have administrator access.")}`)}redirect("/admin")}
export async function signOut(){const db=await createSupabaseServerClient();await db.auth.signOut();redirect("/admin/login")}
export async function createContent(form:FormData){const {db}=await requireAdmin();const parsed=contentSchema.safeParse({title:form.get("title"),contentText:form.get("contentText"),isActive:form.get("isActive")==="on"});if(!parsed.success)redirect(`/admin?section=content&error=${encodeURIComponent(parsed.error.issues[0]?.message||"Invalid content.")}`);const value=parsed.data;const {error}=await db.rpc("admin_create_tamil_content",{p_title:value.title,p_content_text:value.contentText,p_is_active:value.isActive});if(error)redirect(`/admin?section=content&error=${encodeURIComponent(error.message)}`);revalidatePath("/admin");redirect("/admin?section=content&success=Content%20saved%20successfully.")}
export async function toggleContent(form:FormData){const {db,user}=await requireAdmin();const id=String(form.get("id")),active=form.get("active")==="true";const {data,error}=await db.from("tamil_contents").update({is_active:!active,updated_at:new Date().toISOString()}).eq("id",id).select().single();if(error)throw error;await db.from("audit_logs").insert({actor_id:user.id,action:active?"disable":"enable",entity_type:"tamil_content",entity_id:id,new_data:data});revalidatePath("/admin")}
export async function deleteContent(form:FormData){const {db,user}=await requireAdmin();const id=String(form.get("id"));const {data}=await db.from("tamil_contents").delete().eq("id",id).select().single();await db.from("audit_logs").insert({actor_id:user.id,action:"delete",entity_type:"tamil_content",entity_id:id,old_data:data});revalidatePath("/admin")}

export async function updateContent(form:FormData){const {db,user}=await requireAdmin();const id=String(form.get("id"));const value=contentSchema.parse({title:form.get("title"),contentText:form.get("contentText"),isActive:form.get("isActive")==="on"});const {data:old}=await db.from("tamil_contents").select("*").eq("id",id).single();const {data,error}=await db.from("tamil_contents").update({title:value.title,content_text:value.contentText,is_active:value.isActive,updated_at:new Date().toISOString()}).eq("id",id).select().single();if(error)throw error;await db.from("audit_logs").insert({actor_id:user.id,action:"update",entity_type:"tamil_content",entity_id:id,old_data:old,new_data:data});revalidatePath("/admin")}

export async function uploadBranding(form:FormData){const {db,user}=await requireAdmin();const file=form.get("symbol");if(!(file instanceof File)||file.size===0)throw new Error("Choose an image file.");if(!["image/png","image/jpeg","image/webp"].includes(file.type)||file.size>5*1024*1024)throw new Error("Use PNG, JPG, or WebP under 5 MB.");const ext=file.name.split(".").pop()?.toLowerCase()||"png",path=`party-symbol/${crypto.randomUUID()}.${ext}`;const {error:uploadError}=await db.storage.from("branding").upload(path,file,{contentType:file.type,upsert:false});if(uploadError)throw uploadError;const {data:{publicUrl}}=db.storage.from("branding").getPublicUrl(path);await db.from("branding_assets").update({is_active:false,updated_at:new Date().toISOString()}).eq("asset_type","party_symbol");const {data,error}=await db.from("branding_assets").insert({asset_type:"party_symbol",asset_url:publicUrl,storage_path:path,is_active:true,created_by:user.id}).select().single();if(error)throw error;await db.from("audit_logs").insert({actor_id:user.id,action:"upload",entity_type:"branding_asset",entity_id:data.id,new_data:data});revalidatePath("/admin")}

export async function toggleBranding(form:FormData){const {db,user}=await requireAdmin();const id=String(form.get("id")),active=form.get("active")==="true";if(!active)await db.from("branding_assets").update({is_active:false,updated_at:new Date().toISOString()}).eq("asset_type","party_symbol");const {data,error}=await db.from("branding_assets").update({is_active:!active,updated_at:new Date().toISOString()}).eq("id",id).select().single();if(error)throw error;await db.from("audit_logs").insert({actor_id:user.id,action:active?"disable":"enable",entity_type:"branding_asset",entity_id:id,new_data:data});revalidatePath("/admin")}

export async function toggleTemplate(form:FormData){const {db,user}=await requireAdmin();const id=String(form.get("id")),active=form.get("active")==="true";const {data,error}=await db.from("poster_templates").update({is_active:!active,updated_at:new Date().toISOString()}).eq("id",id).select().single();if(error)throw error;await db.from("audit_logs").insert({actor_id:user.id,action:active?"disable":"enable",entity_type:"poster_template",entity_id:id,new_data:data});revalidatePath("/admin")}

export async function updateDailyLimit(form:FormData){const {db,user}=await requireAdmin();const limit=Number(form.get("limit"));if(!Number.isInteger(limit)||limit<1||limit>20)throw new Error("Daily limit must be between 1 and 20.");const {data,error}=await db.from("app_settings").upsert({key:"daily_download_limit",value:limit,updated_by:user.id,updated_at:new Date().toISOString()}).select().single();if(error)throw error;await db.from("audit_logs").insert({actor_id:user.id,action:"update",entity_type:"setting",entity_id:"daily_download_limit",new_data:data});revalidatePath("/admin")}
