import Link from "next/link";
/* eslint-disable @next/next/no-img-element -- admin displays storage assets */
import { redirect } from "next/navigation";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { createContent,deleteContent,signOut,toggleBranding,toggleContent,toggleTemplate,updateContent,updateDailyLimit,uploadBranding } from "./actions";
export const dynamic="force-dynamic";
type Section="overview"|"content"|"branding"|"templates"|"downloads"|"settings";
const NAV:[Section,string][]=[["overview","Overview"],["content","Tamil content"],["branding","Branding"],["templates","Templates"],["downloads","Downloads"],["settings","Settings"]];

export default async function Admin({searchParams}:{searchParams:Promise<{section?:Section;q?:string;error?:string;success?:string}>}){
 const db=await createSupabaseServerClient(),{data:{user}}=await db.auth.getUser();if(!user)redirect("/admin/login");
 const {data:isAdmin}=await db.rpc("is_admin");if(!isAdmin)redirect("/admin/login?error=Administrator%20access%20required.");
 const {section="overview",q="",error:actionError,success}=await searchParams;
 let contentQuery=db.from("tamil_contents").select("*").order("updated_at",{ascending:false});if(q)contentQuery=contentQuery.or(`title.ilike.%${q}%,content_text.ilike.%${q}%`);
 const [{data:contents},{data:downloads},{data:assets},{data:templates},{data:setting},{data:audits}]=await Promise.all([
  contentQuery,
  db.from("download_records").select("id,phone_number_hash,phone_last4,template_key,output_format,india_day,created_at,tamil_contents(title)").order("created_at",{ascending:false}).limit(100),
  db.from("branding_assets").select("*").order("created_at",{ascending:false}),
  db.from("poster_templates").select("*").order("format").order("name"),
  db.from("app_settings").select("value").eq("key","daily_download_limit").single(),
  db.from("audit_logs").select("action,entity_type,created_at").order("created_at",{ascending:false}).limit(8)
 ]);
 const today=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata"}).format(new Date()),todayDownloads=downloads?.filter(d=>d.india_day===today).length??0,activeContent=contents?.filter(c=>c.is_active).length??0;
 return <main className="min-h-screen bg-[#f4f1eb] lg:grid lg:grid-cols-[260px_1fr]">
  <aside className="bg-[#171411] p-5 text-white lg:min-h-screen"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#b42327] text-xl font-black">த</span><div><b className="block">Tamil Poster</b><small className="text-white/45">Administration</small></div></div><nav className="mt-8 grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-1">{NAV.map(([key,label])=><Link key={key} href={`/admin?section=${key}`} className={`rounded-xl px-4 py-3 text-sm font-bold ${section===key?"bg-white text-[#171411]":"text-white/65 hover:bg-white/8 hover:text-white"}`}>{label}</Link>)}</nav><div className="mt-8 border-t border-white/10 pt-5"><p className="truncate text-xs text-white/45">{user.email}</p><form action={signOut}><button className="mt-3 w-full rounded-xl border border-white/15 px-4 py-2 text-sm font-bold">Sign out</button></form></div></aside>
  <div className="min-w-0 p-4 sm:p-7 lg:p-10"><header className="mb-7"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#b42327]">Protected workspace</p><h1 className="mt-2 text-3xl font-black">{NAV.find(([key])=>key===section)?.[1]}</h1></header>{actionError&&<p role="alert" className="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-800">{actionError}</p>}{success&&<p className="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-800">{success}</p>}
  {section==="overview"&&<><Stats active={activeContent} today={todayDownloads} total={downloads?.length??0} assets={assets?.filter(a=>a.is_active).length??0}/><div className="mt-6 grid gap-6 lg:grid-cols-2"><Panel title="System status"><Status label="Approved content available" ok={activeContent>0}/><Status label="Authorized symbol active" ok={Boolean(assets?.some(a=>a.is_active))}/><Status label="Active poster templates" ok={Boolean(templates?.some(t=>t.is_active))}/><Status label="Download limit configured" ok={Boolean(setting?.value)}/></Panel><Panel title="Recent admin activity">{audits?.length?audits.map((a,i)=><div key={i} className="flex justify-between border-b border-black/8 py-3 text-sm last:border-0"><span className="font-semibold capitalize">{a.action} {a.entity_type.replaceAll("_"," ")}</span><span className="text-black/40">{new Date(a.created_at).toLocaleDateString("en-IN")}</span></div>):<Empty text="No administrative activity yet."/>}</Panel></div></>}
  {section==="content"&&<div className="grid gap-6 xl:grid-cols-[380px_1fr]"><Panel title="Add approved content"><p className="mb-5 text-sm text-black/50">Review every message before enabling it.</p><form action={createContent} className="space-y-4"><Field label="Internal title" name="title"/><Area label="Tamil poster message" name="contentText"/><CheckField label="Enable after saving" name="isActive"/><Submit label="Save content"/></form></Panel><section className="card overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-black/10 p-5"><div><h2 className="font-black">Content library</h2><p className="text-sm text-black/45">{contents?.length??0} items · {activeContent} active</p></div><form><input type="hidden" name="section" value="content"/><input className="field w-56" name="q" defaultValue={q} placeholder="Search…"/></form></div><div className="divide-y divide-black/8">{contents?.length?contents.map(c=><details key={c.id} className="group p-5"><summary className="flex cursor-pointer list-none items-start justify-between gap-4"><div><div className="flex items-center gap-2"><b>{c.title}</b><Badge active={c.is_active}/></div><p className="mt-2 line-clamp-2 leading-7 text-black/70">{c.content_text}</p></div><span className="text-sm font-bold text-[#b42327]">Edit</span></summary><form action={updateContent} className="mt-5 grid gap-4 rounded-2xl bg-black/[.025] p-4"><input type="hidden" name="id" value={c.id}/><Field label="Title" name="title" value={c.title}/><Area label="Message" name="contentText" value={c.content_text}/><CheckField label="Active" name="isActive" checked={c.is_active}/><div className="flex flex-wrap gap-2"><Submit label="Save changes" small/><button formAction={toggleContent} name="active" value={String(c.is_active)} className="rounded-xl border border-black/10 bg-white px-4 py-2 text-sm font-bold">{c.is_active?"Disable":"Enable"}</button><button formAction={deleteContent} className="rounded-xl border border-red-200 bg-white px-4 py-2 text-sm font-bold text-red-700">Delete</button></div></form></details>):<Empty text="No Tamil content found."/>}</div></section></div>}
  {section==="branding"&&<div className="grid gap-6 lg:grid-cols-[380px_1fr]"><Panel title="Upload authorized symbol"><p className="mb-5 text-sm leading-6 text-black/50">Upload only an officially supplied asset that you have permission to use. A new upload becomes the active symbol.</p><form action={uploadBranding} className="space-y-4"><label className="block"><span className="label">Symbol image</span><input className="field" type="file" name="symbol" accept="image/png,image/jpeg,image/webp" required/></label><Submit label="Upload and activate"/></form></Panel><Panel title="Branding assets">{assets?.length?<div className="grid gap-4 sm:grid-cols-2">{assets.map(a=><article key={a.id} className="rounded-2xl border border-black/10 bg-white p-4"><div className="grid h-36 place-items-center rounded-xl bg-black/[.035]"><img src={a.asset_url} alt="Authorized branding asset" className="max-h-28 max-w-[80%] object-contain"/></div><div className="mt-3 flex items-center justify-between"><Badge active={a.is_active}/><form action={toggleBranding}><input type="hidden" name="id" value={a.id}/><input type="hidden" name="active" value={String(a.is_active)}/><button className="text-sm font-bold text-[#b42327]">{a.is_active?"Disable":"Activate"}</button></form></div></article>)}</div>:<Empty text="No authorized branding asset uploaded."/>}</Panel></div>}
  {section==="templates"&&<Panel title="Poster templates"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{templates?.map(t=><article key={t.id} className="rounded-2xl border border-black/10 bg-white p-5"><div className="flex items-start justify-between"><div><b>{t.name}</b><p className="mt-1 text-sm capitalize text-black/45">{t.format} · {t.width} × {t.height}</p></div><Badge active={t.is_active}/></div><form action={toggleTemplate} className="mt-5"><input type="hidden" name="id" value={t.id}/><input type="hidden" name="active" value={String(t.is_active)}/><button className="w-full rounded-xl border border-black/10 px-4 py-2 text-sm font-bold">{t.is_active?"Disable template":"Enable template"}</button></form></article>)}</div></Panel>}
  {section==="downloads"&&<Panel title="Download history"><p className="mb-5 text-sm leading-6 text-black/50">Phone numbers are deliberately masked. The secure hash is used for limit enforcement; full phone numbers are not retained.</p><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead><tr className="border-b border-black/10 text-black/45"><Th>Phone</Th><Th>Content</Th><Th>Template</Th><Th>Format</Th><Th>India date</Th><Th>Time</Th></tr></thead><tbody>{downloads?.map(d=><tr key={d.id} className="border-b border-black/6"><Td>••••••{d.phone_last4??"••••"}</Td><Td>{Array.isArray(d.tamil_contents)?d.tamil_contents[0]?.title:(d.tamil_contents as {title?:string}|null)?.title??"—"}</Td><Td>{d.template_key}</Td><Td><span className="capitalize">{d.output_format}</span></Td><Td>{d.india_day}</Td><Td>{new Date(d.created_at).toLocaleString("en-IN")}</Td></tr>)}</tbody></table>{!downloads?.length&&<Empty text="No successful downloads recorded yet."/>}</div></Panel>}
  {section==="settings"&&<div className="max-w-lg"><Panel title="Daily download limit"><p className="mb-5 text-sm leading-6 text-black/50">Applied per phone hash per Asia/Kolkata calendar day. Without OTP, ownership of a number is not verified.</p><form action={updateDailyLimit} className="space-y-4"><label><span className="label">Downloads per day</span><input className="field" type="number" min="1" max="20" name="limit" defaultValue={String(setting?.value??3)} required/></label><Submit label="Save setting"/></form></Panel></div>}
  </div></main>
}

function Stats({active,today,total,assets}:{active:number;today:number;total:number;assets:number}){return <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Active Tamil content" value={active}/><Stat label="Downloads today" value={today}/><Stat label="Recent downloads" value={total}/><Stat label="Active branding" value={assets}/></section>}
function Stat({label,value}:{label:string;value:number}){return <div className="card p-5"><p className="text-sm font-semibold text-black/45">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="card p-5 sm:p-6"><h2 className="mb-4 text-lg font-black">{title}</h2>{children}</section>}
function Field({label,name,value}:{label:string;name:string;value?:string}){return <label className="block"><span className="label">{label}</span><input className="field" name={name} defaultValue={value} maxLength={100} required/></label>}
function Area({label,name,value}:{label:string;name:string;value?:string}){return <label className="block"><span className="label">{label}</span><textarea className="field min-h-32 resize-y" name={name} defaultValue={value} maxLength={500} required/></label>}
function CheckField({label,name,checked}:{label:string;name:string;checked?:boolean}){return <label className="flex items-center gap-3 text-sm font-semibold"><input type="checkbox" name={name} defaultChecked={checked} className="size-4 accent-[#b42327]"/>{label}</label>}
function Submit({label,small}:{label:string;small?:boolean}){return <button className={`rounded-xl bg-[#b42327] font-bold text-white ${small?"px-4 py-2 text-sm":"w-full p-3"}`}>{label}</button>}
function Badge({active}:{active:boolean}){return <span className={`rounded-full px-2 py-1 text-xs font-bold ${active?"bg-emerald-100 text-emerald-800":"bg-black/5 text-black/45"}`}>{active?"Active":"Disabled"}</span>}
function Status({label,ok}:{label:string;ok:boolean}){return <div className="flex items-center justify-between border-b border-black/8 py-3 text-sm last:border-0"><span className="font-semibold">{label}</span><Badge active={ok}/></div>}
function Empty({text}:{text:string}){return <p className="p-6 text-center text-sm text-black/45">{text}</p>}
function Th({children}:{children:React.ReactNode}){return <th className="px-3 py-3 font-bold">{children}</th>}
function Td({children}:{children:React.ReactNode}){return <td className="px-3 py-3">{children}</td>}
