"use client";
/* eslint-disable @next/next/no-img-element -- local previews use blob URLs */
import { ChangeEvent,useEffect,useRef,useState } from "react";
import { ArrowRight,Check,Download,ImagePlus,LockKeyhole,ShieldCheck,Sparkles } from "lucide-react";
import { FORMATS,PosterFormat,renderPoster,TemplateKey,TEMPLATES } from "@/lib/poster";
type Selection={id:string;contentText:string;symbolUrl?:string|null};
export function PosterGenerator(){
 const canvas=useRef<HTMLCanvasElement>(null);const[step,setStep]=useState(0),[name,setName]=useState(""),[designation,setDesignation]=useState(""),[photo,setPhoto]=useState(""),[format,setFormat]=useState<PosterFormat>("whatsapp"),[template,setTemplate]=useState<TemplateKey>("rising-sun"),[selection,setSelection]=useState<Selection|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[phone,setPhone]=useState(""),[consent,setConsent]=useState(false),[modal,setModal]=useState(false),[remaining,setRemaining]=useState<number|null>(null);
 useEffect(()=>{if(selection&&canvas.current&&photo)renderPoster(canvas.current,{fullName:name,designation,photoUrl:photo,format,template,approvedContent:selection.contentText,symbolUrl:selection.symbolUrl}).catch(()=>setError("Poster preview could not be rendered."))},[selection,name,designation,photo,format,template]);
 function upload(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;if(!file.type.startsWith("image/")||file.size>8*1024*1024){setError("Choose a JPG, PNG, or WebP image under 8 MB.");return}if(photo)URL.revokeObjectURL(photo);setPhoto(URL.createObjectURL(file));setError("")}
 function next(){if(!name.trim()||!designation.trim()||!photo){setError("Complete all three fields to continue.");return}setError("");setStep(1)}
 async function generate(){setBusy(true);setError("");try{const r=await fetch("/api/content/random",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({template,format})}),d=await r.json();if(!r.ok)throw new Error(d.error);setSelection(d);setStep(2)}catch(e){setError(e instanceof Error?e.message:"Generation failed.")}finally{setBusy(false)}}
 async function download(){if(!consent){setError("Please consent to daily-limit processing.");return}setBusy(true);setError("");try{const r=await fetch("/api/downloads/authorize",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({phone,templateId:template,contentId:selection?.id,format})}),d=await r.json();if(!r.ok)throw new Error(d.error);if(!canvas.current)throw new Error("Poster is not ready.");const a=document.createElement("a");a.download=`tamil-poster-${format}-${new Date().toISOString().slice(0,10)}.png`;a.href=canvas.current.toDataURL("image/png");a.click();setRemaining(d.remaining);setModal(false)}catch(e){setError(e instanceof Error?e.message:"Download failed.")}finally{setBusy(false)}}
 return <main className="min-h-screen"><header className="border-b border-black/8 bg-white/70 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 sm:px-6"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-[#b42327] text-xl font-black text-white">த</div><div><p className="font-black leading-none">தமிழ் போஸ்டர்</p><p className="mt-1 text-xs text-black/50">Approved poster studio</p></div></div><a href="/admin" className="focus-ring flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-semibold text-black/60 hover:bg-black/5"><LockKeyhole size={15}/> Admin</a></div></header>
 <div className="mx-auto max-w-7xl px-4 py-7 sm:px-6 lg:py-10"><div className="mb-6 flex items-end justify-between gap-4"><div><p className="mb-2 text-xs font-bold uppercase tracking-[.22em] text-[#b42327]">Poster studio</p><h1 className="max-w-xl text-3xl font-black tracking-tight sm:text-4xl">Create your poster in minutes.</h1></div><div className="hidden items-center gap-2 text-sm text-black/55 md:flex"><ShieldCheck size={17} className="text-[#b42327]"/> Approved content only</div></div>
 <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(360px,.72fr)]"><section className="card overflow-hidden"><div className="flex border-b border-black/8 bg-white/60">{["Details","Template","Preview"].map((x,i)=><button key={x} onClick={()=>i<2&&setStep(i)} className={`flex flex-1 items-center justify-center gap-2 px-2 py-4 text-sm font-bold ${step===i?"border-b-2 border-[#b42327] text-[#b42327]":"text-black/40"}`}><span className={`grid size-6 place-items-center rounded-full text-xs ${i<step?"bg-[#b42327] text-white":"bg-black/6"}`}>{i<step?<Check size={13}/>:i+1}</span>{x}</button>)}</div><div className="p-5 sm:p-7">
 {step===0&&<div className="space-y-5"><Title title="Your details" text="Only these personal fields appear on the poster."/><label><span className="label">Full name</span><input className="field" maxLength={60} value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Prakash"/></label><label><span className="label">Designation</span><input className="field" maxLength={90} value={designation} onChange={e=>setDesignation(e.target.value)} placeholder="சமூக சேவகர் | சென்னை"/></label><Photo photo={photo} upload={upload}/><Primary onClick={next}>Choose template <ArrowRight size={18}/></Primary></div>}
 {step===1&&<div className="space-y-6"><Title title="Format & design" text="Protected text and branding remain locked."/><fieldset><legend className="label">Output format</legend><div className="grid grid-cols-2 gap-3">{Object.entries(FORMATS).map(([k,v])=><button key={k} onClick={()=>setFormat(k as PosterFormat)} className={`rounded-2xl border p-4 text-left ${format===k?"border-[#b42327] bg-[#b42327]/5":"border-black/10 bg-white"}`}><b className="block text-sm">{v.label}</b><span className="mt-1 block text-xs text-black/45">{v.width} × {v.height} · {v.ratio}</span></button>)}</div></fieldset><fieldset><legend className="label">Poster design</legend><div className="space-y-3">{TEMPLATES.map(t=><button key={t.id} onClick={()=>setTemplate(t.id)} className={`flex w-full items-center gap-4 rounded-2xl border p-3 text-left ${template===t.id?"border-[#b42327] bg-[#b42327]/5":"border-black/10 bg-white"}`}><span className={`h-14 w-11 rounded-lg ${t.id==="heritage"?"border-4 border-[#8e1c24] bg-[#f2e8d5]":t.id==="modern-lines"?"bg-[linear-gradient(#b42327_18%,#f5f2ea_18%,#f5f2ea_82%,#b42327_82%)]":"bg-[linear-gradient(155deg,#b42327_0_26%,#171411_26%)]"}`}/><span className="flex-1"><b className="block">{t.name}</b><small className="text-black/45">{t.note}</small></span>{template===t.id&&<Check className="text-[#b42327]" size={18}/>}</button>)}</div></fieldset><Primary onClick={generate} disabled={busy}><Sparkles size={18}/>{busy?"Selecting approved content…":"Generate poster"}</Primary></div>}
 {step===2&&<div className="space-y-5"><Title title="Ready to download" text="Edit your personal details; approved content stays locked."/><div className="grid gap-4 sm:grid-cols-2"><label><span className="label">Full name</span><input className="field" value={name} maxLength={60} onChange={e=>setName(e.target.value)}/></label><label><span className="label">Designation</span><input className="field" value={designation} maxLength={90} onChange={e=>setDesignation(e.target.value)}/></label></div><Photo photo={photo} upload={upload}/><button onClick={generate} className="rounded-xl border border-black/10 bg-white px-4 py-2.5 text-sm font-bold"><Sparkles className="mr-2 inline" size={16}/>New approved message</button>{remaining!==null&&<p className="rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-800">Downloads remaining today: {remaining} / 3</p>}<Primary onClick={()=>setModal(true)}><Download size={18}/>Download PNG</Primary></div>}{error&&<p role="alert" className="mt-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-semibold text-red-800">{error}</p>}</div></section>
 <aside className="card flex min-h-[34rem] flex-col p-4 sm:p-5"><div className="mb-4 flex items-center justify-between"><div><b>Live preview</b><p className="text-xs text-black/45">Final PNG uses exact dimensions</p></div><span className="rounded-full bg-[#d49a29]/15 px-3 py-1 text-xs font-bold text-[#8b6216]">{FORMATS[format].ratio}</span></div><div className="grid flex-1 place-items-center overflow-hidden rounded-2xl bg-[#e8e3da] p-4">{selection?<canvas ref={canvas} className="poster-enter max-h-[65vh] max-w-full rounded-lg shadow-2xl" aria-label="Generated poster preview"/>:<div className="max-w-xs text-center"><div className="mx-auto mb-4 grid size-16 place-items-center rounded-2xl bg-white shadow-sm"><ImagePlus className="text-black/35"/></div><b>Your poster will appear here</b><p className="mt-2 text-sm leading-6 text-black/45">Add your details, choose a protected template, and generate.</p></div>}</div></aside></div><p className="mx-auto mt-7 max-w-3xl text-center text-xs leading-5 text-black/45">Political content and branding come only from the administrator-approved library. Phone collection without OTP is not identity verification.</p></div>
 {modal&&<div className="fixed inset-0 z-50 grid place-items-end bg-black/55 sm:place-items-center sm:p-4"><section role="dialog" aria-modal="true" className="w-full max-w-md rounded-t-3xl bg-white p-6 sm:rounded-3xl"><Title title="Download your poster" text="Enter an Indian mobile number. It is used only for the daily limit and is not verified by OTP."/><label className="mt-5 block"><span className="label">Mobile number</span><div className="flex"><span className="grid place-items-center rounded-l-xl border border-r-0 border-black/15 px-3 font-bold">+91</span><input className="field rounded-l-none" inputMode="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="98765 43210"/></div></label><label className="mt-4 flex items-start gap-3 text-sm"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} className="mt-1 accent-[#b42327]"/>I consent to processing this number to enforce the 3-download daily limit.</label><div className="mt-6 grid grid-cols-2 gap-3"><button onClick={()=>setModal(false)} className="rounded-xl border border-black/10 p-3 font-bold">Cancel</button><button onClick={download} disabled={busy} className="rounded-xl bg-[#b42327] p-3 font-bold text-white">{busy?"Checking…":"Authorize"}</button></div></section></div>}</main>}
function Title({title,text}:{title:string;text:string}){return <div><h2 className="text-xl font-black">{title}</h2><p className="mt-1 text-sm leading-6 text-black/55">{text}</p></div>}
function Photo({photo,upload}:{photo:string;upload:(e:ChangeEvent<HTMLInputElement>)=>void}){return <label className="block"><span className="label">Personal photo</span><span className="flex cursor-pointer items-center gap-4 rounded-2xl border border-dashed border-black/20 bg-black/[.025] p-4">{photo?<img src={photo} alt="Selected" className="size-20 rounded-xl object-cover"/>:<span className="grid size-14 place-items-center rounded-xl bg-white"><ImagePlus size={22}/></span>}<span><b className="block">{photo?"Change photo":"Choose a clear portrait"}</b><small className="text-black/50">JPG, PNG or WebP · max 8 MB</small></span><input className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" onChange={upload}/></span></label>}
function Primary({children,onClick,disabled}:{children:React.ReactNode;onClick:()=>void;disabled?:boolean}){return <button onClick={onClick} disabled={disabled} className="flex w-full items-center justify-center gap-2 rounded-2xl bg-[#b42327] px-5 py-3.5 font-bold text-white hover:bg-[#941d21]">{children}</button>}
